import XCTest
@testable import COIL

/// Tier 2 PR C-1: tests for the v2 knowledge-graph loader + merge logic.
///
/// Tests the pure `KnowledgeGraphService.merge(v1:v2:)` function and the
/// feature-flag gating. Does NOT exercise the actual v2 file loading from
/// the app bundle — that's tested implicitly by the existing
/// `KnowledgeGraphServiceTests` (which load the real v1 file).
///
/// The real production v2 file lives at
/// `Resources/medical_knowledge_graph_v2.json` and is generated by
/// `scripts/expand_knowledge_graph.py` after PR C-2 ships. Until then,
/// the loader's v2-merge path is exercised here with hand-built fixtures.
final class KnowledgeGraphExpansionTests: XCTestCase {

    // MARK: - Fixtures

    /// Minimal v1-shape graph: one condition (knee), small alias list.
    private func makeV1() -> KnowledgeGraph {
        let pfps = KnownCondition(
            names: ["patellofemoral pain syndrome", "pfps"],
            icd10: "M22.2X9",
            bodyRegions: ["knee"],
            safeExercises: ["quad-sets", "straight-leg-raises"],
            unsafeExercises: ["bulgarian-split-squat"],
            redFlags: ["knee locking"],
            referIfPresent: ["symptoms > 8 weeks"]
        )
        return KnowledgeGraph(
            version: "1.0",
            conditions: ["patellofemoral-pain-syndrome": pfps],
            exercises: nil
        )
    }

    /// v2 fixture: same condition with EXTRA exercises + a new condition.
    private func makeV2() -> KnowledgeGraph {
        let pfpsV2 = KnownCondition(
            names: ["pfps", "kneecap pain"],  // partial alias overlap with v1
            icd10: "M22.2X9",
            bodyRegions: ["knee"],
            safeExercises: ["mini-squats", "wall-sits", "quad-sets"],  // overlap + new
            unsafeExercises: ["deep-knee-bend"],  // new contraindication
            redFlags: [],
            referIfPresent: []
        )
        let fibro = KnownCondition(
            names: ["fibromyalgia", "fibro"],
            icd10: "M79.7",
            bodyRegions: ["systemic"],
            safeExercises: ["low-impact-walking", "warm-water-aerobics"],
            unsafeExercises: ["high-intensity-interval-training"],
            redFlags: ["new neurological symptoms"],
            referIfPresent: ["symptoms worsen despite paced activity"]
        )
        return KnowledgeGraph(
            version: "2.0-test",
            conditions: [
                "patellofemoral-pain-syndrome": pfpsV2,
                "fibromyalgia": fibro,
            ],
            exercises: nil
        )
    }

    // MARK: - merge() — overlap behavior

    func test_merge_overlapping_unionsSafeExercises() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        let pfps = merged.conditions["patellofemoral-pain-syndrome"]
        XCTAssertNotNil(pfps)
        // v1: [quad-sets, straight-leg-raises], v2: [mini-squats, wall-sits, quad-sets]
        // Union: [quad-sets, straight-leg-raises, mini-squats, wall-sits]
        XCTAssertEqual(Set(pfps!.safeExercises), Set([
            "quad-sets",
            "straight-leg-raises",
            "mini-squats",
            "wall-sits",
        ]))
    }

    func test_merge_overlapping_unionsUnsafeExercises() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        let pfps = merged.conditions["patellofemoral-pain-syndrome"]!
        // v1: [bulgarian-split-squat], v2: [deep-knee-bend] — both retained
        XCTAssertEqual(Set(pfps.unsafeExercises), Set(["bulgarian-split-squat", "deep-knee-bend"]))
    }

    func test_merge_overlapping_unionsAliasNames() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        let pfps = merged.conditions["patellofemoral-pain-syndrome"]!
        // v1: ["patellofemoral pain syndrome", "pfps"], v2 adds: ["kneecap pain"]
        XCTAssertEqual(Set(pfps.names), Set([
            "patellofemoral pain syndrome",
            "pfps",
            "kneecap pain",
        ]))
    }

    func test_merge_overlapping_preservesV1RedFlags() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        let pfps = merged.conditions["patellofemoral-pain-syndrome"]!
        // v2 had no red flags for this condition; v1's must survive.
        XCTAssertTrue(pfps.redFlags.contains("knee locking"))
    }

    // MARK: - merge() — v2-only condition

    func test_merge_v2OnlyCondition_addedAsIs() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        let fibro = merged.conditions["fibromyalgia"]
        XCTAssertNotNil(fibro)
        XCTAssertEqual(fibro?.icd10, "M79.7")
        XCTAssertTrue(fibro?.safeExercises.contains("low-impact-walking") ?? false)
    }

    // MARK: - merge() — v1-only condition

    func test_merge_v1OnlyCondition_preserved() {
        let v1 = makeV1()
        // v2 with NO conditions: any v1 condition must survive untouched.
        let v2 = KnowledgeGraph(version: "2.0-empty", conditions: [:], exercises: nil)
        let merged = KnowledgeGraphService.merge(v1: v1, v2: v2)
        XCTAssertEqual(merged.conditions.count, 1)
        XCTAssertNotNil(merged.conditions["patellofemoral-pain-syndrome"])
    }

    // MARK: - merge() — empty v2 is a no-op

    func test_merge_emptyV2_doesNotShrinkV1() {
        let v1 = makeV1()
        let empty = KnowledgeGraph(version: "2.0-empty", conditions: [:], exercises: nil)
        let merged = KnowledgeGraphService.merge(v1: v1, v2: empty)

        let v1Pfps = v1.conditions["patellofemoral-pain-syndrome"]!
        let mergedPfps = merged.conditions["patellofemoral-pain-syndrome"]!
        XCTAssertEqual(Set(mergedPfps.safeExercises), Set(v1Pfps.safeExercises))
        XCTAssertEqual(Set(mergedPfps.unsafeExercises), Set(v1Pfps.unsafeExercises))
        XCTAssertEqual(Set(mergedPfps.redFlags), Set(v1Pfps.redFlags))
    }

    // MARK: - merge() — version string records sources

    func test_merge_versionStringMentionsBothSources() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        XCTAssertTrue(merged.version.contains("v1=1.0"))
        XCTAssertTrue(merged.version.contains("v2=2.0-test"))
    }

    // MARK: - merge() — verify() integration on the merged graph

    func test_merge_verify_v2OnlySafeExercisePassesAfterMerge() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        let svc = KnowledgeGraphService(graph: merged)
        // mini-squats was added in v2 only; should be .verified after merge.
        XCTAssertEqual(
            svc.verify(exercise: "mini-squats", forCondition: "patellofemoral-pain-syndrome"),
            .verified
        )
    }

    func test_merge_verify_v1ContraindicationStillFiresAfterMerge() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        let svc = KnowledgeGraphService(graph: merged)
        // bulgarian-split-squat was contraindicated in v1; must remain so after merge.
        let result = svc.verify(exercise: "bulgarian-split-squat", forCondition: "patellofemoral-pain-syndrome")
        if case .contraindicated = result {
            // expected
        } else {
            XCTFail("Expected .contraindicated, got \(result)")
        }
    }

    func test_merge_verify_v2OnlyConditionWorks() {
        let merged = KnowledgeGraphService.merge(v1: makeV1(), v2: makeV2())
        let svc = KnowledgeGraphService(graph: merged)
        // Fibromyalgia exists only in v2 — must be lookup-able after merge.
        XCTAssertEqual(
            svc.verify(exercise: "low-impact-walking", forCondition: "fibromyalgia"),
            .verified
        )
    }

    // MARK: - Feature flag

    func test_featureFlag_defaultsOff() {
        // Use a test-isolated UserDefaults key check rather than the real
        // helper — we don't want to mutate UserDefaults in CI. The contract:
        // .isEnabled returns false when the key is absent.
        let suiteName = "kg-flag-test-\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName)!
        XCTAssertFalse(defaults.bool(forKey: KnowledgeGraphFeatureFlag.key))
        // Cleanup
        defaults.removePersistentDomain(forName: suiteName)
    }

    func test_featureFlag_keyMatchesAppStoragePattern() {
        // The key must match exactly what an iOS view would use with
        // @AppStorage("knowledgeGraphV2Enabled"). Any rename here breaks
        // the runtime gating.
        XCTAssertEqual(KnowledgeGraphFeatureFlag.key, "knowledgeGraphV2Enabled")
    }
}
