/**
 * Codegen: read scripts/output/exercise_image_mapping.json (the source of truth for
 * what images we have) and emit functions/src/generated/exerciseCatalog.ts as a
 * compact 3-column CSV string.
 *
 * The CSV is injected into the rehab_plan / exercise_substitute / wellness_plan
 * system prompts as a cacheable block so Claude is constrained to picking from
 * the catalog rather than inventing kebab-case names that may not have images.
 *
 * Format: `display_name|normalized_filename|target_area\n` per row.
 *   - display_name + normalized_filename are required for Claude to populate
 *     the per-exercise `name` and `imageFileName` fields.
 *   - target_area is required for the kinetic-chain fallback instruction in
 *     the prompt; without it, Claude cannot tell which entries are anatomically
 *     adjacent to the patient's primary region.
 *   - category is intentionally dropped — the prompt already has an
 *     `exerciseCategory` enum rule and Claude derives it from context.
 *   - aliases are intentionally dropped — they're for client-side resolution
 *     of historical names, not for prompting (sending them invites Claude
 *     to pick aliases instead of canonical names).
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

const REPO_ROOT = resolve(__dirname, "..", "..");
const SOURCE = resolve(REPO_ROOT, "scripts", "output", "exercise_image_mapping.json");
const OUT = resolve(__dirname, "..", "src", "generated", "exerciseCatalog.ts");

interface MappingEntry {
  name: string;
  filename: string;
  category: string;
  target_area: string;
  body_position?: string;
  aliases?: string[];
  end_filename?: string;
}

function escapeBacktick(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

function main(): void {
  const raw = readFileSync(SOURCE, "utf8");
  const mapping = JSON.parse(raw) as Record<string, MappingEntry>;

  // Sorted by canonical key so the output is deterministic across runs.
  const keys = Object.keys(mapping).sort();
  const rows: string[] = [];
  for (const key of keys) {
    const entry = mapping[key];
    // Defensive: any of these being empty would be a bug in the catalog,
    // but we'd rather fail the build cleanly than ship a malformed prompt.
    if (!entry.name || !entry.target_area) {
      throw new Error(`Catalog entry missing fields: ${key}`);
    }
    // Strip pipes from data so they cannot collide with the column delimiter.
    const name = entry.name.replace(/\|/g, "/");
    const targetArea = entry.target_area.replace(/\|/g, "/");
    rows.push(`${name}|${key}|${targetArea}`);
  }

  const csv = rows.join("\n");
  const banner = "// AUTO-GENERATED by functions/scripts/build_catalog.ts — do NOT edit by hand.";
  const file = `${banner}
// Source: scripts/output/exercise_image_mapping.json
// Format: display_name|normalized_filename|target_area
// Run \`npm run build\` (which fires the prebuild hook) to regenerate.

export const EXERCISE_CATALOG_CSV: string = \`${escapeBacktick(csv)}\`;

export const EXERCISE_CATALOG_ENTRY_COUNT = ${keys.length};
`;

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, file, "utf8");

  console.log(`Wrote ${keys.length} catalog entries → ${OUT}`);
  console.log(`Catalog CSV size: ${csv.length} bytes (~${Math.round(csv.length / 4)} tokens)`);
}

main();
