"""
Tier 2 PR C-1 — local review UI for knowledge-graph v2 verdicts.

Walks the human reviewer through every `contraindicated` verdict
generated by `expand_knowledge_graph.py`, plus a deterministic 10% sample
of `safe` verdicts. Per the Tier 2 plan this review step is a HARD STOP
before the v2 file can be promoted to the iOS bundle.

Decisions saved live (each click → POST → file write) to
`scripts/output/kg_review_decisions.json`. Resume-friendly: re-running the
tool picks up where the last session left off.

Verdicts the reviewer can apply:
  - APPROVE  → keep as-is
  - REJECT   → drop this verdict from the merged v2 (treat as unverified)
  - FLIP     → flip safe ↔ contraindicated (use only when the AI is
               clearly wrong about direction)
  - EDIT     → free-text override of the reason (rarely needed)

When done, run `scripts/merge_kg_review.py` (separate small script,
intentionally NOT created in PR C-1 because we want explicit human
review of the merge step too) to produce the final v2 graph.

Usage:
  python scripts/review_kg_candidates.py
  python scripts/review_kg_candidates.py --port 5302
  python scripts/review_kg_candidates.py --safe-sample-percent 20
"""
from __future__ import annotations

import argparse
import json
import random
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR / "output"
DRAFT_INPUT = OUTPUT_DIR / "knowledge_graph_v2_draft.json"
DECISIONS_FILE = OUTPUT_DIR / "kg_review_decisions.json"

DEFAULT_SAFE_SAMPLE_PERCENT = 10
RANDOM_SEED = 42  # deterministic sample so the same verdicts get reviewed across re-runs


# ---------------------------------------------------------------------------
# Decision storage
# ---------------------------------------------------------------------------

def load_decisions() -> dict:
    if DECISIONS_FILE.exists():
        try:
            return json.loads(DECISIONS_FILE.read_text())
        except json.JSONDecodeError:
            return {}
    return {}


def save_decisions(decisions: dict) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    DECISIONS_FILE.write_text(json.dumps(decisions, indent=2, sort_keys=True))


def decision_key(verdict_row: dict) -> str:
    return f"{verdict_row['condition_id']}|{verdict_row['exercise_id']}"


# ---------------------------------------------------------------------------
# Build the review queue: all contraindicated + 10% of safe
# ---------------------------------------------------------------------------

def build_entries(safe_sample_percent: int) -> list[dict]:
    if not DRAFT_INPUT.exists():
        raise SystemExit(
            f"ERROR: {DRAFT_INPUT} not found.\n"
            "Run `scripts/expand_knowledge_graph.py` first to generate the draft."
        )
    draft = json.loads(DRAFT_INPUT.read_text())
    verdicts = draft.get("verdicts", [])

    contraindicated = [v for v in verdicts if v.get("verdict") == "contraindicated"]
    safe = [v for v in verdicts if v.get("verdict") == "safe"]
    unclear = [v for v in verdicts if v.get("verdict") == "unclear"]

    # Deterministic sample of safes
    rng = random.Random(RANDOM_SEED)
    sample_n = max(0, len(safe) * safe_sample_percent // 100)
    safe_sample = rng.sample(safe, sample_n) if sample_n < len(safe) else safe[:]

    # Also surface ALL "unclear" verdicts — these are the ones the AI itself
    # punted on, so a human should make the call.
    queue = []
    for row in contraindicated:
        queue.append({**row, "review_bucket": "contraindicated"})
    for row in unclear:
        queue.append({**row, "review_bucket": "unclear"})
    for row in safe_sample:
        queue.append({**row, "review_bucket": "safe-sample"})

    decisions = load_decisions()
    for entry in queue:
        key = decision_key(entry)
        prior = decisions.get(key)
        entry["current_decision"] = prior.get("decision", "pending") if prior else "pending"
        entry["edited_reason"] = prior.get("edited_reason") if prior else None

    print(
        f"Review queue: {len(contraindicated)} contraindicated + "
        f"{len(unclear)} unclear + {len(safe_sample)}/{len(safe)} sampled safes "
        f"= {len(queue)} entries"
    )
    return queue


# ---------------------------------------------------------------------------
# HTML / JS UI
# ---------------------------------------------------------------------------

HTML = """<!doctype html><html><head><meta charset=utf-8><title>KG Review</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; margin: 0; background: #0f1115; color: #e5e7eb; }}
  header {{ position: sticky; top: 0; background: #111827; padding: 12px 24px; border-bottom: 1px solid #1f2937; display: flex; gap: 24px; align-items: center; z-index: 10; }}
  header h1 {{ font-size: 16px; margin: 0; font-weight: 600; }}
  header .counts {{ font-size: 13px; color: #9ca3af; }}
  header .keys {{ font-size: 11px; color: #6b7280; margin-left: auto; }}
  header button {{ background: #2563eb; color: white; border: 0; padding: 6px 12px; border-radius: 6px; cursor: pointer; font-weight: 500; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(440px, 1fr)); gap: 16px; padding: 16px; }}
  .card {{ background: #1f2937; border-radius: 10px; padding: 14px; border: 2px solid transparent; transition: border 0.1s; }}
  .card.approve  {{ border-color: #16a34a; }}
  .card.reject   {{ border-color: #dc2626; }}
  .card.flip     {{ border-color: #f59e0b; }}
  .card.focused  {{ box-shadow: 0 0 0 2px #60a5fa; }}
  .bucket {{ display: inline-block; font-size: 10px; font-weight: 700; padding: 2px 6px; border-radius: 4px; text-transform: uppercase; letter-spacing: 0.04em; }}
  .bucket.contraindicated {{ background: #7f1d1d; color: #fecaca; }}
  .bucket.unclear         {{ background: #78350f; color: #fde68a; }}
  .bucket.safe-sample     {{ background: #14532d; color: #bbf7d0; }}
  .verdict {{ display: inline-block; font-size: 11px; padding: 2px 6px; border-radius: 4px; margin-left: 8px; font-weight: 600; }}
  .verdict.contraindicated {{ background: #7f1d1d; color: #fecaca; }}
  .verdict.unclear         {{ background: #78350f; color: #fde68a; }}
  .verdict.safe            {{ background: #14532d; color: #bbf7d0; }}
  .pair {{ font-family: ui-monospace, monospace; font-size: 13px; margin: 8px 0; }}
  .pair .cond {{ color: #fbbf24; }}
  .pair .ex {{ color: #86efac; }}
  .reason {{ color: #d1d5db; font-size: 13px; line-height: 1.4; margin: 8px 0; padding: 8px; background: #111827; border-radius: 5px; }}
  .severity {{ color: #9ca3af; font-size: 11px; font-style: italic; }}
  .editbox {{ width: 100%; box-sizing: border-box; padding: 6px; border: 1px solid #374151; background: #111827; color: #e5e7eb; border-radius: 4px; font-family: inherit; font-size: 12px; margin-top: 6px; resize: vertical; }}
  .buttons {{ display: flex; gap: 6px; margin-top: 10px; }}
  .buttons button {{ flex: 1; padding: 6px 4px; border-radius: 5px; border: 1px solid #374151; background: #111827; color: #e5e7eb; cursor: pointer; font-weight: 500; font-size: 12px; }}
  .buttons button.active.approve {{ background: #16a34a; border-color: #16a34a; color: white; }}
  .buttons button.active.reject  {{ background: #dc2626; border-color: #dc2626; color: white; }}
  .buttons button.active.flip    {{ background: #f59e0b; border-color: #f59e0b; color: white; }}
  .idx {{ color: #6b7280; font-size: 10px; font-family: ui-monospace, monospace; }}
</style></head>
<body>
<header>
  <h1>KG verdict review</h1>
  <div class=counts id=counts></div>
  <button onclick="window.location='/export'">Download decisions</button>
  <div class=keys>A=Approve · R=Reject · F=Flip · E=Edit · ← →</div>
</header>
<div class=grid id=grid></div>
<script>
const entries = {entries_json};
let focused = 0;

function update(i, decision) {{
  entries[i].current_decision = decision;
  fetch('/decide', {{method:'POST', headers:{{'content-type':'application/json'}}, body: JSON.stringify({{
    key: entries[i].condition_id + '|' + entries[i].exercise_id,
    decision,
    edited_reason: entries[i].edited_reason || null,
  }})}});
  render();
}}

function saveEdit(i, value) {{
  entries[i].edited_reason = value;
  fetch('/decide', {{method:'POST', headers:{{'content-type':'application/json'}}, body: JSON.stringify({{
    key: entries[i].condition_id + '|' + entries[i].exercise_id,
    decision: entries[i].current_decision || 'pending',
    edited_reason: value,
  }})}});
}}

function focusCard(i) {{
  focused = Math.max(0, Math.min(entries.length - 1, i));
  render();
  document.querySelectorAll('.card')[focused]?.scrollIntoView({{block:'nearest', behavior:'smooth'}});
}}

function render() {{
  const grid = document.getElementById('grid');
  const approves = entries.filter(e => e.current_decision === 'approve').length;
  const rejects  = entries.filter(e => e.current_decision === 'reject').length;
  const flips    = entries.filter(e => e.current_decision === 'flip').length;
  const pending  = entries.filter(e => e.current_decision === 'pending').length;
  document.getElementById('counts').textContent =
    `${{approves}} approve · ${{rejects}} reject · ${{flips}} flip · ${{pending}} pending · ${{entries.length}} total`;
  grid.innerHTML = entries.map((e, i) => {{
    const focusedCls = i === focused ? 'focused' : '';
    const decisionCls = e.current_decision !== 'pending' ? e.current_decision : '';
    const sev = e.contraindication_severity ? `<span class=severity>severity: ${{e.contraindication_severity}}</span>` : '';
    return `
      <div class="card ${{decisionCls}} ${{focusedCls}}" onclick="focusCard(${{i}})">
        <div class=idx>${{i + 1}}/${{entries.length}}</div>
        <span class="bucket ${{e.review_bucket}}">${{e.review_bucket}}</span>
        <span class="verdict ${{e.verdict}}">${{e.verdict}}</span>
        <div class=pair>
          <span class=cond>${{e.condition_id}}</span> × <span class=ex>${{e.exercise_id}}</span>
        </div>
        <div class=reason>${{e.reason}}</div>
        ${{sev}}
        <textarea class=editbox rows=2 placeholder="Override reason (optional)…"
                  onclick="event.stopPropagation()"
                  oninput="saveEdit(${{i}}, this.value)">${{e.edited_reason || ''}}</textarea>
        <div class=buttons>
          <button class="approve ${{e.current_decision === 'approve' ? 'active' : ''}}"
                  onclick="event.stopPropagation();update(${{i}},'approve')">Approve</button>
          <button class="reject ${{e.current_decision === 'reject' ? 'active' : ''}}"
                  onclick="event.stopPropagation();update(${{i}},'reject')">Reject</button>
          <button class="flip ${{e.current_decision === 'flip' ? 'active' : ''}}"
                  onclick="event.stopPropagation();update(${{i}},'flip')">Flip</button>
        </div>
      </div>`;
  }}).join('');
}}

document.addEventListener('keydown', e => {{
  if (e.target.tagName === 'TEXTAREA') return;
  if      (e.key === 'a' || e.key === 'A') {{ update(focused, 'approve'); focusCard(focused + 1); }}
  else if (e.key === 'r' || e.key === 'R') {{ update(focused, 'reject');  focusCard(focused + 1); }}
  else if (e.key === 'f' || e.key === 'F') {{ update(focused, 'flip');    focusCard(focused + 1); }}
  else if (e.key === 'e' || e.key === 'E') {{
    document.querySelectorAll('.card')[focused]?.querySelector('textarea')?.focus();
    e.preventDefault();
  }}
  else if (e.key === 'ArrowRight') focusCard(focused + 1);
  else if (e.key === 'ArrowLeft')  focusCard(focused - 1);
  else if (e.key === 'ArrowDown')  focusCard(focused + 3);
  else if (e.key === 'ArrowUp')    focusCard(focused - 3);
}});

render();
</script>
</body></html>"""


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------

def make_handler(safe_sample_percent: int):
    class Handler(SimpleHTTPRequestHandler):
        def log_message(self, *a, **kw):
            pass

        def do_GET(self):
            url = urlparse(self.path)
            if url.path == "/":
                entries = build_entries(safe_sample_percent)
                body = HTML.format(entries_json=json.dumps(entries)).encode()
                self.send_response(200)
                self.send_header("content-type", "text/html; charset=utf-8")
                self.send_header("content-length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif url.path == "/export":
                data = (DECISIONS_FILE.read_bytes() if DECISIONS_FILE.exists() else b"{}\n")
                self.send_response(200)
                self.send_header("content-type", "application/json")
                self.send_header("content-disposition",
                                 'attachment; filename="kg_review_decisions.json"')
                self.send_header("content-length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
            else:
                self.send_error(404)

        def do_POST(self):
            if self.path != "/decide":
                self.send_error(404)
                return
            length = int(self.headers.get("content-length", "0"))
            payload = json.loads(self.rfile.read(length))
            decisions = load_decisions()
            decisions[payload["key"]] = {
                "decision": payload["decision"],
                "edited_reason": payload.get("edited_reason"),
            }
            save_decisions(decisions)
            self.send_response(204)
            self.end_headers()

    return Handler


def main() -> int:
    parser = argparse.ArgumentParser(description="Review KG v2 verdicts in a localhost UI")
    parser.add_argument("--port", type=int, default=5302)
    parser.add_argument("--safe-sample-percent", type=int, default=DEFAULT_SAFE_SAMPLE_PERCENT,
                        help=f"%% of 'safe' verdicts to sample for review (default {DEFAULT_SAFE_SAMPLE_PERCENT})")
    args = parser.parse_args()

    if not DRAFT_INPUT.exists():
        print(f"ERROR: {DRAFT_INPUT.relative_to(SCRIPT_DIR.parent)} not found.")
        print("Run `scripts/expand_knowledge_graph.py` first.")
        return 1

    print(f"\nKG review server: http://localhost:{args.port}/")
    print(f"Decisions save live to {DECISIONS_FILE.relative_to(SCRIPT_DIR.parent)}")
    print("Use the 'Download decisions' button when finished, then run the merge step.\n")
    HTTPServer(("127.0.0.1", args.port), make_handler(args.safe_sample_percent)).serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
